import type { Property } from "@/lib/types";

const broker = {
  name: "Ricardo Albuquerque",
  creci: "CRECI 98.765-F",
  avatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-2.jpg",
};

const now = "2026-01-01T12:00:00.000Z";

export const seedProperties: Property[] = [
  {
    id: "prop-mansao-horizon-glass",
    slug: "mansao-horizon-glass",
    title: "Mansão Horizon Glass",
    location: "Vila Nova, Costa Verde",
    locationFull: "Vila Nova, Costa Verde — Angra dos Reis, RJ",
    city: "Rio de Janeiro",
    neighborhood: "Vila Nova",
    state: "RJ",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Casa",
    typeLabel: "Casa",
    price: 14500000,
    priceLabel: "R$ 14.500.000",
    ref: "VAL-00192",
    status: "Publicado",
    bedrooms: 5,
    suites: 5,
    bathrooms: 6,
    parking: 6,
    area: 1250,
    builtArea: 850,
    landArea: 1250,
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_a754c8470c_39071eb1de954ced.png",
    images: [
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_a754c8470c_1541df02abe63121.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_e15226778b_95c2f049778ba13f.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_8a1b38c963_c0592031f86498a3.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_6c9e71a6c0_3a21fbaa648f3f51.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_f5976d78e6_442c340eb3878071.png",
    ],
    featured: true,
    highlight: true,
    description: [
      "A Mansão Horizon Glass é uma verdadeira obra-prima da arquitetura contemporânea, projetada para oferecer uma experiência de vida inigualável. Com uma integração total entre os ambientes internos e a exuberante natureza ao redor, cada detalhe foi pensado para maximizar a entrada de luz natural e a vista panorâmica para o oceano.",
      "O projeto utiliza materiais nobres como concreto aparente, madeira certificada e amplos painéis de vidro de alta performance. A área social é composta por salas amplas com pé-direito duplo, lareira suspensa e cozinha gourmet integrada equipada com aparelhos de última geração.",
    ],
    condo: "R$ 4.500",
    iptu: "R$ 12.000 (ano)",
    rooms: [
      "5 Quartos",
      "5 Suítes",
      "6 Banheiros",
      "Sala de Estar",
      "Sala de Jantar",
      "Cozinha Gourmet",
      "Escritório",
      "Lavanderia",
      "Lavabo",
      "Dependência",
    ],
    leisure: [
      "Jardim Tropical",
      "Varanda Gourmet",
      "Piscina com Borda Infinita",
      "Churrasqueira",
      "Área Gourmet",
      "Terraço",
      "Deck de Madeira",
      "Sauna Seca",
    ],
    extras: [
      "Semimobiliado",
      "Aquecimento Central",
      "Ar-condicionado Split",
      "Sistema de Segurança",
      "Posição Solar Norte",
      "Acabamento em Pedra",
    ],
    proximities: [
      "Escola Bilíngue",
      "Supermercado Premium",
      "Marina Privativa",
      "Hospital de Referência",
      "Restaurantes Estrelados",
    ],
    broker,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop-penthouse-jardins",
    slug: "penthouse-jardins",
    title: "Penthouse Jardins",
    location: "Jardim das Acácias, Litoral",
    locationFull: "Jardim das Acácias, Litoral — São Paulo, SP",
    city: "São Paulo",
    neighborhood: "Jardins",
    state: "SP",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Apartamento",
    typeLabel: "Apartamento",
    price: 4250000,
    priceLabel: "R$ 4.250.000",
    ref: "2024042",
    status: "Publicado",
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parking: 2,
    area: 320,
    builtArea: 280,
    landArea: 0,
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_3216a91907_2a5aa469a1d08b3e.png",
    images: [
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_3216a91907_2a5aa469a1d08b3e.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_e15226778b_95c2f049778ba13f.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_8a1b38c963_c0592031f86498a3.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_6c9e71a6c0_3a21fbaa648f3f51.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_f5976d78e6_442c340eb3878071.png",
    ],
    featured: true,
    highlight: false,
    description: [
      "Penthouse sofisticada com vista privilegiada, ambientes integrados e acabamentos de alto padrão. Ideal para quem busca conforto urbano com a tranquilidade de um endereço exclusivo.",
      "A planta valoriza a luz natural e a convivência, com varanda ampla, suítes generosas e living com pé-direito elevado.",
    ],
    condo: "R$ 2.800",
    iptu: "R$ 8.400 (ano)",
    rooms: ["3 Quartos", "3 Suítes", "4 Banheiros", "Sala de Estar", "Cozinha Gourmet", "Lavabo"],
    leisure: ["Varanda Gourmet", "Piscina", "Academia", "Salão de Festas"],
    extras: ["Ar-condicionado Split", "Sistema de Segurança", "Mobiliado parcialmente"],
    proximities: ["Escola Bilíngue", "Supermercado Premium", "Restaurantes Estrelados"],
    broker,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop-duplex-centro-historico",
    slug: "duplex-centro-historico",
    title: "Duplex Centro Histórico",
    location: "Centro Histórico, Capital",
    locationFull: "Centro Histórico, Capital — São Paulo, SP",
    city: "São Paulo",
    neighborhood: "Centro Histórico",
    state: "SP",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Cobertura",
    typeLabel: "Cobertura",
    price: 3100000,
    priceLabel: "R$ 3.100.000",
    ref: "2024088",
    status: "Publicado",
    bedrooms: 2,
    suites: 2,
    bathrooms: 3,
    parking: 2,
    area: 180,
    builtArea: 180,
    landArea: 0,
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_4683d84348_f37107d4690a185d.png",
    images: [
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_4683d84348_f37107d4690a185d.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_e15226778b_95c2f049778ba13f.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_8a1b38c963_c0592031f86498a3.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_6c9e71a6c0_3a21fbaa648f3f51.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_f5976d78e6_442c340eb3878071.png",
    ],
    featured: true,
    highlight: false,
    description: [
      "Duplex contemporâneo no coração da cidade, com design minimalista, grandes vãos de vidro e um living pensado para receber.",
      "A cobertura combina privacidade e proximidade com a vida cultural da capital.",
    ],
    condo: "R$ 1.900",
    iptu: "R$ 6.200 (ano)",
    rooms: ["2 Quartos", "2 Suítes", "3 Banheiros", "Sala de Estar", "Cozinha Gourmet"],
    leisure: ["Terraço", "Área Gourmet", "Deck de Madeira"],
    extras: ["Ar-condicionado Split", "Sistema de Segurança"],
    proximities: ["Restaurantes Estrelados", "Hospital de Referência", "Supermercado Premium"],
    broker,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop-vila-do-sol",
    slug: "vila-do-sol",
    title: "Vila do Sol",
    location: "Costa Verde, RJ",
    locationFull: "Costa Verde — Rio de Janeiro, RJ",
    city: "Rio de Janeiro",
    neighborhood: "Costa Verde",
    state: "RJ",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Casa",
    typeLabel: "Casa de Praia",
    price: 6800000,
    priceLabel: "R$ 6.800.000",
    ref: "2024102",
    status: "Publicado",
    bedrooms: 4,
    suites: 4,
    bathrooms: 5,
    parking: 4,
    area: 450,
    builtArea: 380,
    landArea: 450,
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_589ea0d9b6_da721bc0699f0957.png",
    images: [
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_589ea0d9b6_da721bc0699f0957.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_e15226778b_95c2f049778ba13f.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_8a1b38c963_c0592031f86498a3.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_6c9e71a6c0_3a21fbaa648f3f51.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_f5976d78e6_442c340eb3878071.png",
    ],
    featured: true,
    highlight: false,
    description: [
      "Casa de praia com piscina, deck de madeira e integração total com a natureza. Um refúgio sofisticado na Costa Verde.",
      "Ambientes amplos, suítes com vista e área gourmet para receber em qualquer estação.",
    ],
    condo: "R$ 0",
    iptu: "R$ 9.800 (ano)",
    rooms: ["4 Quartos", "4 Suítes", "5 Banheiros", "Sala de Estar", "Cozinha Gourmet"],
    leisure: ["Piscina", "Deck de Madeira", "Churrasqueira", "Jardim Tropical"],
    extras: ["Ar-condicionado Split", "Sistema de Segurança"],
    proximities: ["Marina Privativa", "Restaurantes Estrelados"],
    broker,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop-residencia-concrete",
    slug: "residencia-concrete",
    title: "Residência Concrete",
    location: "Alto de Pinheiros, SP",
    locationFull: "Alto de Pinheiros — São Paulo, SP",
    city: "São Paulo",
    neighborhood: "Alto de Pinheiros",
    state: "SP",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Casa",
    typeLabel: "Casa Moderna",
    price: 7900000,
    priceLabel: "R$ 7.900.000",
    ref: "2024155",
    status: "Publicado",
    bedrooms: 4,
    suites: 4,
    bathrooms: 4,
    parking: 3,
    area: 520,
    builtArea: 420,
    landArea: 520,
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_00c39fa1c6_177ffc7cab7e57c1.png",
    images: [
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_00c39fa1c6_177ffc7cab7e57c1.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_e15226778b_95c2f049778ba13f.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_8a1b38c963_c0592031f86498a3.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_6c9e71a6c0_3a21fbaa648f3f51.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_f5976d78e6_442c340eb3878071.png",
    ],
    featured: false,
    highlight: false,
    description: [
      "Residência contemporânea em concreto aparente, com grandes vãos de vidro e jardim tropical. Arquitetura brutalista sofisticada.",
      "Planta generosa, suítes com vista para o verde e living integrado à área externa.",
    ],
    condo: "R$ 0",
    iptu: "R$ 11.000 (ano)",
    rooms: ["4 Quartos", "4 Suítes", "4 Banheiros", "Sala de Estar", "Escritório"],
    leisure: ["Jardim Tropical", "Piscina", "Área Gourmet"],
    extras: ["Aquecimento Central", "Sistema de Segurança"],
    proximities: ["Escola Bilíngue", "Supermercado Premium", "Hospital de Referência"],
    broker,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prop-urban-loft",
    slug: "urban-loft",
    title: "Urban Loft",
    location: "Vila Madalena, SP",
    locationFull: "Vila Madalena — São Paulo, SP",
    city: "São Paulo",
    neighborhood: "Vila Madalena",
    state: "SP",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Apartamento",
    typeLabel: "Loft",
    price: 1850000,
    priceLabel: "R$ 1.850.000",
    ref: "2024189",
    status: "Publicado",
    bedrooms: 1,
    suites: 1,
    bathrooms: 2,
    parking: 1,
    area: 120,
    builtArea: 120,
    landArea: 0,
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_7b34bee21b_abe734c6b8ca01db.png",
    images: [
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_7b34bee21b_abe734c6b8ca01db.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_e15226778b_95c2f049778ba13f.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_8a1b38c963_c0592031f86498a3.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_6c9e71a6c0_3a21fbaa648f3f51.png",
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/gen_f5976d78e6_442c340eb3878071.png",
    ],
    featured: false,
    highlight: false,
    description: [
      "Loft urbano com pé-direito alto, tijolo aparente e grandes janelas industriais. Um endereço vibrante na Vila Madalena.",
      "Espaço integrado, iluminação natural abundante e acabamento contemporâneo.",
    ],
    condo: "R$ 980",
    iptu: "R$ 3.200 (ano)",
    rooms: ["1 Quarto", "1 Suíte", "2 Banheiros", "Sala integrada"],
    leisure: ["Terraço"],
    extras: ["Ar-condicionado Split"],
    proximities: ["Restaurantes Estrelados", "Supermercado Premium"],
    broker,
    createdAt: now,
    updatedAt: now,
  },
];
