import type { Property } from "@/lib/types";

const now = "2026-01-01T12:00:00.000Z";

export const sampleProperties: Property[] = [
  {
    id: "p1",
    slug: "casa-centro-curitiba",
    title: "Casa Centro",
    location: "Centro, Curitiba",
    locationFull: "Centro, Curitiba — Curitiba, PR",
    city: "Curitiba",
    neighborhood: "Centro",
    state: "PR",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Casa",
    typeLabel: "Casa",
    price: 850_000,
    priceLabel: "R$ 850.000",
    ref: "VAL-001",
    status: "Publicado",
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parking: 2,
    area: 180,
    builtArea: 160,
    landArea: 180,
    image: "/img1.jpg",
    images: ["/img1.jpg"],
    featured: true,
    highlight: true,
    description: ["Casa no centro."],
    condo: "",
    iptu: "",
    rooms: [],
    leisure: [],
    extras: [],
    proximities: [],
    broker: { name: "Corretor", creci: "CRECI 1", avatar: "" },
    createdAt: now,
    updatedAt: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "p2",
    slug: "apto-batel",
    title: "Apartamento Batel",
    location: "Batel, Curitiba",
    locationFull: "Batel, Curitiba — Curitiba, PR",
    city: "Curitiba",
    neighborhood: "Batel",
    state: "PR",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Apartamento",
    typeLabel: "Apartamento",
    price: 1_200_000,
    priceLabel: "R$ 1.200.000",
    ref: "VAL-002",
    status: "Publicado",
    bedrooms: 2,
    suites: 2,
    bathrooms: 3,
    parking: 1,
    area: 95,
    builtArea: 95,
    landArea: 0,
    image: "/img2.jpg",
    images: ["/img2.jpg"],
    featured: false,
    highlight: false,
    description: ["Apto no Batel."],
    condo: "",
    iptu: "",
    rooms: [],
    leisure: [],
    extras: [],
    proximities: [],
    broker: { name: "Corretor", creci: "CRECI 1", avatar: "" },
    createdAt: now,
    updatedAt: "2026-03-01T12:00:00.000Z",
  },
  {
    id: "p3",
    slug: "terreno-rascunho",
    title: "Terreno Rascunho",
    location: "Pinhais, Curitiba",
    locationFull: "Pinhais — Curitiba, PR",
    city: "Pinhais",
    neighborhood: "Centro",
    state: "PR",
    cep: "",
    address: "",
    number: "",
    latitude: "",
    longitude: "",
    type: "Terreno",
    typeLabel: "Terreno",
    price: 300_000,
    priceLabel: "R$ 300.000",
    ref: "VAL-003",
    status: "Rascunho",
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    parking: 0,
    area: 500,
    builtArea: 0,
    landArea: 500,
    image: "",
    images: [],
    featured: false,
    highlight: false,
    description: [],
    condo: "",
    iptu: "",
    rooms: [],
    leisure: [],
    extras: [],
    proximities: [],
    broker: { name: "Corretor", creci: "CRECI 1", avatar: "" },
    createdAt: now,
    updatedAt: now,
  },
];
